name: 'valyrie-thread-action'
description: 'Triggers a thread in a Discord channel.'

inputs:
  threadName:
    description: 'The name of the thread.'
    required: true
  channelName:
    description: 'The name of the channel to create the thread in.'
    required: true
  message:
    description: 'The message to send in the thread.'
    required: false
    default: '.'
  webhookUrl:
    description: 'The webhook url to send the message to.'
    required: true
  webhookAuth:
    required: true

runs:
  using: node20
  main: dist/index.js
